export const MAINBOOKSDATA = 'MAINBOOKSDATA';
export const CLASSIFICATIONDATA = 'CLASSIFICATIONDATA';
export const BOOKMARKDATA = 'BOOKMARKDATA';
export const SEARCHDATA = 'SEARCHDATA';
export const TOTALHADITHDATA = 'TOTALHADITHDATA';
export const SIMILARDATA = 'SIMILARDATA';

export const CLEARMAINDATA = 'CLEARMAINDATA';
export const CLEARKITABDATA = 'CLEARKITABDATA';
export const CLEARBABDATA = 'CLEARBABDATA';
export const CLEAROTHERNUMBER = 'CLEAROTHERNUMBER';

export const KITABDATA = 'KITABDATA';
export const BABDATA = 'BABDATA';
export const SHOWNKITABVALUE = 'SHOWNKITABVALUE';
export const SHOWNBABVALUE = 'SHOWNBABVALUE';
export const CURRENTTABLE = 'CURRENTTABLE';

export const POSITION = 'POSITION';
export const TOTALROW = 'TOTALROW';
export const CHANGENUMBER = 'CHANGENUMBER';

export const DISABLEFIRSTPREV = 'DISABLEFIRSTPREV';
export const DISABLELASTNEXT = 'DISABLELASTNEXT';

export const OTHERNUMBER = 'OTHERNUMBER';
export const SHOWINPUTOTHERNUMBER = 'SHOWINPUTOTHERNUMBER';
export const OTHERNUMBERTOSEARCH = 'OTHERNUMBERTOSEARCH';

export const OPENSNACKBARS = 'OPENSNACKBARS';
export const PUSHTOQUEUE = 'PUSHTOQUEUE';

export const NUMBEREACHBOOKS = 'NUMBEREACHBOOKS';

export const INDEXLEFTTAB = 'INDEXLEFTTAB';
export const INDEXRIGHTTAB = 'INDEXRIGHTTAB';

export const EXPANDCOLLAPSE = 'EXPANDCOLLAPSE';

export const RADIOCHECKED = 'RADIOCHECKED';
export const RADIOMODECARICHECKED = 'RADIOMODECARICHECKED';

export const NEWTITLE = 'NEWTITLE';
export const EXISTTITLE = 'EXISTTITLE';
export const TITLEFORLOAD = 'TITLEFORLOAD';
export const STORELISTTITLE = 'STORELISTTITLE';

export const BOOKMARKLIST = 'BOOKMARKLIST';
export const BOOKMARKTABLE = 'BOOKMARKTABLE';
export const UNBOOKMARK = 'UNBOOKMARK';

export const CHECKALL = 'CHECKALL';
export const CHECKALLNOT = 'CHECKALLNOT';
export const CHECKBUKHARI = 'CHECKBUKHARI';
export const CHECKMUSLIM = 'CHECKMUSLIM';
export const CHECKTIRMIDZI = 'CHECKTIRMIDZI';
export const CHECKABUDAUD = 'CHECKABUDAUD';
export const CHECKNASAI = 'CHECKNASAI';
export const CHECKIBNUMAJAH = 'CHECKIBNUMAJAH';
export const CHECKDARIMI = 'CHECKDARIMI';
export const CHECKAHMAD = 'CHECKAHMAD';
export const CHECKMALIK = 'CHECKMALIK';
export const CHECKDARUQUTHNI = 'CHECKDARUQUTHNI';
export const CHECKIBNUKHUZAIMAH = 'CHECKIBNUKHUZAIMAH';
export const CHECKIBNUHIBBAN = 'CHECKIBNUHIBBAN';
export const CHECKALMUSTADRAK = 'CHECKALMUSTADRAK';
export const CHECKSYAFII = 'CHECKSYAFII';

export const SEARCHRESULT = 'SEARCHRESULT';
export const CLEARSEARCHRESULT = 'CLEARSEARCHRESULT';
export const SEARCHVALUE = 'SEARCHVALUE';
export const SELECTIONINDEX = 'SELECTIONINDEX';

export const AMOUNTBUKHARI = 'AMOUNTBUKHARI';
export const AMOUNTMUSLIM = 'AMOUNTMUSLIM';
export const AMOUNTTIRMIDZI = 'AMOUNTTIRMIDZI';
export const AMOUNTABUDAUD = 'AMOUNTABUDAUD';
export const AMOUNTNASAI = 'AMOUNTNASAI';
export const AMOUNTIBNUMAJAH = 'AMOUNTIBNUMAJAH';
export const AMOUNTDARIMI = 'AMOUNTDARIMI';
export const AMOUNTAHMAD = 'AMOUNTAHMAD';
export const AMOUNTMALIK = 'AMOUNTMALIK';
export const AMOUNTDARUQUTHNI = 'AMOUNTDARUQUTHNI';
export const AMOUNTIBNUKHUZAIMAH = 'AMOUNTIBNUKHUZAIMAH';
export const AMOUNTIBNUHIBBAN = 'AMOUNTIBNUHIBBAN';
export const AMOUNTALMUSTADRAK = 'AMOUNTALMUSTADRAK';
export const AMOUNTSYAFII = 'AMOUNTSYAFII';
export const CLEARAMOUNT = 'CLEARAMOUNT';

export const OPENCOMBOKITAB = 'OPENCOMBOKITAB';
export const OPENCOMBOBAB = 'OPENCOMBOBAB';

export const SHOWARABICKEYBOARD = 'SHOWARABICKEYBOARD';

export const SHOWNOTE = 'SHOWNOTE';
export const ANCHORNOTE = 'ANCHORNOTE';
export const NOTEEXIST = 'NOTEEXIST';
export const NOTEVALUE = 'NOTEVALUE';
export const SWITCHNOTEMODE = 'SWITCHNOTEMODE';
export const ALLNOTESDATA = 'ALLNOTESDATA';

export const OPENBIOGRAPHY = 'OPENBIOGRAPHY';
export const TEXTBIOGRAPHY = 'TEXTBIOGRAPHY';

export const OPENINFO = 'OPENINFO';
export const TEXTINFO = 'TEXTINFO';
export const CONTENTINFO = 'CONTENTINFO';

export const SETALLFONT = 'SETALLFONT';
export const SETARABICFONT = 'SETARABICFONT';
export const SETINDOFONT = 'SETINDOFONT';

export const SHOWSANAD = 'SHOWSANAD';
export const SANADDATA = 'SANADDATA';
export const SANADPOSITION = 'SANADPOSITION';
export const SHOWPROFILE = 'SHOWPROFILE';
export const RESIZEBOUND = 'RESIZEBOUND';
export const SELECTEDRAWI = 'SELECTEDRAWI';
export const SCHOLARCOMMENT = 'SCHOLARCOMMENT';

export const NARRATORNAME = 'NARRATORNAME';

export const ANCHORDETAILSCOLOR = 'ANCHORDETAILSCOLOR';
export const SHOWDETAILSCOLOR = 'SHOWDETAILSCOLOR';
export const SELECTEDEXPLANATION = 'SELECTEDEXPLANATION';
export const EXPLANATIONCOLOR = 'EXPLANATIONCOLOR';


export const SHOWDIAGRAMSANAD = 'SHOWDIAGRAMSANAD';

export const SHOWSIMILAR = 'SHOWSIMILAR';
export const SELECTEDSIMILAR = 'SELECTEDSIMILAR';
export const HADITHBEFORESIMILAR = 'HADITHBEFORESIMILAR';

export const NAMEVALUE = 'NAMEVALUE';
export const KUNYAHVALUE = 'KUNYAHVALUE';
export const KALANGANVALUE = 'KALANGANVALUE';
export const LEVELVALUE = 'LEVELVALUE';
export const TABBODYHEIGHTREF = 'TABBODYHEIGHTREF';
export const SEARCHRAWIRESULT = 'SEARCHRAWIRESULT';
export const CLICKEDNARRATOR = 'CLICKEDNARRATOR';
export const ISNARRATORSELECTED = 'ISNARRATORSELECTED';
export const TRIGGERRENDERRAWIRESULT = 'TRIGGERRENDERRAWIRESULT';

export const HADITHTERM = 'HADITHTERM';

export const GLOBALTHEME = 'GLOBALTHEME';
export const LIGHTDARKSWITCH = 'LIGHTDARKSWITCH';
export const LOGIN_STATE = 'LOGIN_STATE';

export const SET_SEARCHING = 'SET_SEARCHING';

export const SEARCHENDPOINTMODE = 'SEARCHENDPOINTMODE';

export const TABDIALOG = 'TABDIALOG';

export const DIALOGPROFILERAWI = 'DIALOGPROFILERAWI';

export const AI_SUMMARY_START = 'AI_SUMMARY_START';
export const AI_SUMMARY_SUCCESS = 'AI_SUMMARY_SUCCESS';
export const AI_SUMMARY_FAIL = 'AI_SUMMARY_FAIL';
export const AI_SUMMARY_CLEAR = 'AI_SUMMARY_CLEAR';

// export const KITABANDBAB = 'KITABANDBAB';

// export const SWIPEABLEINDEX = 'SWIPEABLEINDEX';